### ISSUE TITLE
Runs as root

### ISSUE THREAD

**Issue by nickcmaynard** [nginxinc/docker-nginx-openshift#4]
By default, OpenShift does not allow containers that run as root.  This image runs as root.

Consequently, when attempting to add this to OpenShift, the user sees the following error:
<img width="845" alt="screen shot 2018-06-07 at 21 33 50" src="https://user-images.githubusercontent.com/1984684/41124662-90b07974-6a9a-11e8-8519-b5301afc2620.png">

**Comment by alessfg** [comment]
Hi @nickcmaynard! I think I have identified the issue. The Docker image works if you deploy it via `oc` - however, since it does not explicitly include a USER directive, the default USER is inherited from the parent image (`debian:stretch-slim`) which in this case is the root user. I've created a PR that should fix the issue.
